development:
  clients:
    default:
      database: open_document_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: open_document_api_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false